name: CI/CD - Test et Déploiement automatique

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Configuration Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Téléchargement des ressources NLTK
      run: python nltk_setup.py

    - name: Exécution des tests avec couverture
      run: |
        pytest --cov=app tests/ --cov-report=html

    - name: Archivage du rapport de couverture
      uses: actions/upload-artifact@v3
      with:
        name: rapport-couverture
        path: htmlcov/

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Copier le projet vers le serveur
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        source: "."
        target: "/home/ubuntu/app"

    - name: Déploiement via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/app
          docker compose down || true
          docker compose up -d --build
          echo "✅ Déploiement terminé"
          echo "🩺 Vérification de l’API..."
          curl -sSf http://localhost:5000/ || (echo "❌ L’API ne répond pas" && exit 1)